### ISSUE TITLE
Update docker images 

### ISSUE THREAD

**Issue by theoephraim** [JohnSully/ModJS#4]
Hi @JohnSully!

Thanks for your work on this. keydb is great :)

I'm using the `eqalpha/modjs:keydb-latest` image and it looks like it is using keydb 5.3.3, while `eqalpha/keydb:latest` is at 6.0.16

Looks like the dockerfiles are still good since they pull the latest keydb image, but the images just need to be rebuilt and republished.

Thanks!!

**Comment by benschermel** [comment]
Hi @theoephraim,

Thanks for pointing this out. I have written scripts into our distribution builders to automatically update wrappers whenever we update the KeyDB docker image. This will also update the wrapper for Redis regardless of whether changes were pushed there (tag would remain the same). I am also including historical tags so people know which ModJS version and KeyDB/Redis version are associated with the image.

Closing this issue now as the docker images will be retagged & updated every time the KeyDB docker image is updated. We will also retag and update if a new modjs version is released.

Cheers,

Ben
